package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/tharvid/dvarapala/policies"
)

const defaultInitPolicy = `# Dvarapala policy — generated by 'dvarapala init'
# Edit to taste. Docs: https://github.com/TharVid/dvarapala/blob/main/docs/policy-language.md

version: "1"

defaults:
  - rulepack: destructive-actions   # native — blocks rm -rf, DROP TABLE, etc.

audit:
  format: jsonl
  path: ~/.dvarapala/audit.jsonl
  schema: ocsf

# Add custom rules below.
rules: []
`

func cmdInit(_ context.Context, args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	var (
		out       string
		force     bool
		writePack bool
	)
	fs.StringVar(&out, "policy", defaultPolicyPath(), "where to write policy.yaml")
	fs.BoolVar(&force, "force", false, "overwrite existing file")
	fs.BoolVar(&writePack, "with-packs", false, "also write embedded rule packs alongside policy.yaml (debug)")
	fs.Usage = func() {
		fmt.Fprint(fs.Output(), `Usage: dvarapala init [flags]

Scaffold a default policy file at ~/.dvarapala/policy.yaml. The default
loads the built-in 'destructive-actions' rulepack so 'rm -rf /' and
similar tool calls are denied out of the box.

Flags:
`)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}

	target := expandHome(out)
	if _, err := os.Stat(target); err == nil && !force {
		return fmt.Errorf("%s already exists (use --force to overwrite)", target)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(defaultInitPolicy), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", target)

	if writePack {
		dir := filepath.Join(filepath.Dir(target), "rulepacks")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		entries, err := policies.FS.ReadDir(".")
		if err != nil {
			return err
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			f, err := policies.FS.Open(e.Name())
			if err != nil {
				return err
			}
			b, err := io.ReadAll(f)
			f.Close()
			if err != nil {
				return err
			}
			dst := filepath.Join(dir, e.Name())
			if err := os.WriteFile(dst, b, 0o644); err != nil {
				return err
			}
		}
		fmt.Fprintf(os.Stderr, "wrote %d rulepacks to %s/\n", len(entries), dir)
	}
	return nil
}

func defaultPolicyPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "policy.yaml"
	}
	return filepath.Join(home, ".dvarapala", "policy.yaml")
}
