# This file is a TEMPLATE. The real, version-bumped formula is generated by
# GoReleaser on each release and pushed to https://github.com/tharvid/homebrew-dvarapala
class Dvarapala < Formula
  desc "MCP security gateway — drop-in protection for Model Context Protocol servers"
  homepage "https://github.com/tharvid/dvarapala"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tharvid/dvarapala/releases/download/v#{version}/dvarapala_#{version}_macos_arm64.tar.gz"
      sha256 "REPLACED_BY_GORELEASER"
    end
    on_intel do
      url "https://github.com/tharvid/dvarapala/releases/download/v#{version}/dvarapala_#{version}_macos_x86_64.tar.gz"
      sha256 "REPLACED_BY_GORELEASER"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tharvid/dvarapala/releases/download/v#{version}/dvarapala_#{version}_linux_arm64.tar.gz"
      sha256 "REPLACED_BY_GORELEASER"
    end
    on_intel do
      url "https://github.com/tharvid/dvarapala/releases/download/v#{version}/dvarapala_#{version}_linux_x86_64.tar.gz"
      sha256 "REPLACED_BY_GORELEASER"
    end
  end

  def install
    bin.install "dvarapala"
    pkgshare.install "policies"
  end

  test do
    assert_match "dvarapala", shell_output("#{bin}/dvarapala version")
  end
end
